"""Pulseaudio prototypes."""

# Functions.
functions = {'pa_context_add_autoload': ('pa_operation *',
                             ['pa_context *',
                              'char *',
                              'pa_autoload_type_t',
                              'char *',
                              'char *',
                              'pa_context_index_cb_t',
                              'void *']),
 'pa_context_connect': ('int',
                        ['pa_context *',
                         'char *',
                         'pa_context_flags_t',
                         'pa_spawn_api *']),
 'pa_context_disconnect': ('void', ['pa_context *']),
 'pa_context_drain': ('pa_operation *',
                      ['pa_context *', 'pa_context_notify_cb_t', 'void *']),
 'pa_context_errno': ('int', ['pa_context *']),
 'pa_context_exit_daemon': ('pa_operation *',
                            ['pa_context *',
                             'pa_context_success_cb_t',
                             'void *']),
 'pa_context_get_autoload_info_by_index': ('pa_operation *',
                                           ['pa_context *',
                                            'uint32_t',
                                            'pa_autoload_info_cb_t',
                                            'void *']),
 'pa_context_get_autoload_info_by_name': ('pa_operation *',
                                          ['pa_context *',
                                           'char *',
                                           'pa_autoload_type_t',
                                           'pa_autoload_info_cb_t',
                                           'void *']),
 'pa_context_get_autoload_info_list': ('pa_operation *',
                                       ['pa_context *',
                                        'pa_autoload_info_cb_t',
                                        'void *']),
 'pa_context_get_card_info_by_index': ('pa_operation *',
                                       ['pa_context *',
                                        'uint32_t',
                                        'pa_card_info_cb_t',
                                        'void *']),
 'pa_context_get_card_info_by_name': ('pa_operation *',
                                      ['pa_context *',
                                       'char *',
                                       'pa_card_info_cb_t',
                                       'void *']),
 'pa_context_get_card_info_list': ('pa_operation *',
                                   ['pa_context *',
                                    'pa_card_info_cb_t',
                                    'void *']),
 'pa_context_get_client_info': ('pa_operation *',
                                ['pa_context *',
                                 'uint32_t',
                                 'pa_client_info_cb_t',
                                 'void *']),
 'pa_context_get_client_info_list': ('pa_operation *',
                                     ['pa_context *',
                                      'pa_client_info_cb_t',
                                      'void *']),
 'pa_context_get_index': ('uint32_t', ['pa_context *']),
 'pa_context_get_module_info': ('pa_operation *',
                                ['pa_context *',
                                 'uint32_t',
                                 'pa_module_info_cb_t',
                                 'void *']),
 'pa_context_get_module_info_list': ('pa_operation *',
                                     ['pa_context *',
                                      'pa_module_info_cb_t',
                                      'void *']),
 'pa_context_get_protocol_version': ('uint32_t', ['pa_context *']),
 'pa_context_get_sample_info_by_index': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'pa_sample_info_cb_t',
                                          'void *']),
 'pa_context_get_sample_info_by_name': ('pa_operation *',
                                        ['pa_context *',
                                         'char *',
                                         'pa_sample_info_cb_t',
                                         'void *']),
 'pa_context_get_sample_info_list': ('pa_operation *',
                                     ['pa_context *',
                                      'pa_sample_info_cb_t',
                                      'void *']),
 'pa_context_get_server': ('char *', ['pa_context *']),
 'pa_context_get_server_info': ('pa_operation *',
                                ['pa_context *',
                                 'pa_server_info_cb_t',
                                 'void *']),
 'pa_context_get_server_protocol_version': ('uint32_t', ['pa_context *']),
 'pa_context_get_sink_info_by_index': ('pa_operation *',
                                       ['pa_context *',
                                        'uint32_t',
                                        'pa_sink_info_cb_t',
                                        'void *']),
 'pa_context_get_sink_info_by_name': ('pa_operation *',
                                      ['pa_context *',
                                       'char *',
                                       'pa_sink_info_cb_t',
                                       'void *']),
 'pa_context_get_sink_info_list': ('pa_operation *',
                                   ['pa_context *',
                                    'pa_sink_info_cb_t',
                                    'void *']),
 'pa_context_get_sink_input_info': ('pa_operation *',
                                    ['pa_context *',
                                     'uint32_t',
                                     'pa_sink_input_info_cb_t',
                                     'void *']),
 'pa_context_get_sink_input_info_list': ('pa_operation *',
                                         ['pa_context *',
                                          'pa_sink_input_info_cb_t',
                                          'void *']),
 'pa_context_get_source_info_by_index': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'pa_source_info_cb_t',
                                          'void *']),
 'pa_context_get_source_info_by_name': ('pa_operation *',
                                        ['pa_context *',
                                         'char *',
                                         'pa_source_info_cb_t',
                                         'void *']),
 'pa_context_get_source_info_list': ('pa_operation *',
                                     ['pa_context *',
                                      'pa_source_info_cb_t',
                                      'void *']),
 'pa_context_get_source_output_info': ('pa_operation *',
                                       ['pa_context *',
                                        'uint32_t',
                                        'pa_source_output_info_cb_t',
                                        'void *']),
 'pa_context_get_source_output_info_list': ('pa_operation *',
                                            ['pa_context *',
                                             'pa_source_output_info_cb_t',
                                             'void *']),
 'pa_context_get_state': ('pa_context_state_t', ['pa_context *']),
 'pa_context_get_tile_size': ('size_t', ['pa_context *', 'pa_sample_spec *']),
 'pa_context_is_local': ('int', ['pa_context *']),
 'pa_context_is_pending': ('int', ['pa_context *']),
 'pa_context_kill_client': ('pa_operation *',
                            ['pa_context *',
                             'uint32_t',
                             'pa_context_success_cb_t',
                             'void *']),
 'pa_context_kill_sink_input': ('pa_operation *',
                                ['pa_context *',
                                 'uint32_t',
                                 'pa_context_success_cb_t',
                                 'void *']),
 'pa_context_kill_source_output': ('pa_operation *',
                                   ['pa_context *',
                                    'uint32_t',
                                    'pa_context_success_cb_t',
                                    'void *']),
 'pa_context_load_cookie_from_file': ('int', ['pa_context *', 'char *']),
 'pa_context_load_module': ('pa_operation *',
                            ['pa_context *',
                             'char *',
                             'char *',
                             'pa_context_index_cb_t',
                             'void *']),
 'pa_context_move_sink_input_by_index': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'uint32_t',
                                          'pa_context_success_cb_t',
                                          'void *']),
 'pa_context_move_sink_input_by_name': ('pa_operation *',
                                        ['pa_context *',
                                         'uint32_t',
                                         'char *',
                                         'pa_context_success_cb_t',
                                         'void *']),
 'pa_context_move_source_output_by_index': ('pa_operation *',
                                            ['pa_context *',
                                             'uint32_t',
                                             'uint32_t',
                                             'pa_context_success_cb_t',
                                             'void *']),
 'pa_context_move_source_output_by_name': ('pa_operation *',
                                           ['pa_context *',
                                            'uint32_t',
                                            'char *',
                                            'pa_context_success_cb_t',
                                            'void *']),
 'pa_context_new': ('pa_context *', ['pa_mainloop_api *', 'char *']),
 'pa_context_new_with_proplist': ('pa_context *',
                                  ['pa_mainloop_api *',
                                   'char *',
                                   'pa_proplist *']),
 'pa_context_play_sample': ('pa_operation *',
                            ['pa_context *',
                             'char *',
                             'char *',
                             'pa_volume_t',
                             'pa_context_success_cb_t',
                             'void *']),
 'pa_context_play_sample_with_proplist': ('pa_operation *',
                                          ['pa_context *',
                                           'char *',
                                           'char *',
                                           'pa_volume_t',
                                           'pa_proplist *',
                                           'pa_context_play_sample_cb_t',
                                           'void *']),
 'pa_context_proplist_remove': ('pa_operation *',
                                ['pa_context *',
                                 'char **',
                                 'pa_context_success_cb_t',
                                 'void *']),
 'pa_context_proplist_update': ('pa_operation *',
                                ['pa_context *',
                                 'pa_update_mode_t',
                                 'pa_proplist *',
                                 'pa_context_success_cb_t',
                                 'void *']),
 'pa_context_ref': ('pa_context *', ['pa_context *']),
 'pa_context_remove_autoload_by_index': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'pa_context_success_cb_t',
                                          'void *']),
 'pa_context_remove_autoload_by_name': ('pa_operation *',
                                        ['pa_context *',
                                         'char *',
                                         'pa_autoload_type_t',
                                         'pa_context_success_cb_t',
                                         'void *']),
 'pa_context_remove_sample': ('pa_operation *',
                              ['pa_context *',
                               'char *',
                               'pa_context_success_cb_t',
                               'void *']),
 'pa_context_rttime_new': ('pa_time_event *',
                           ['pa_context *',
                            'pa_usec_t',
                            'pa_time_event_cb_t',
                            'void *']),
 'pa_context_rttime_restart': ('void',
                               ['pa_context *',
                                'pa_time_event *',
                                'pa_usec_t']),
 'pa_context_send_message_to_object': ('pa_operation *',
                                       ['pa_context *',
                                        'char *',
                                        'char *',
                                        'char *',
                                        'pa_context_string_cb_t',
                                        'void *']),
 'pa_context_set_card_profile_by_index': ('pa_operation *',
                                          ['pa_context *',
                                           'uint32_t',
                                           'char *',
                                           'pa_context_success_cb_t',
                                           'void *']),
 'pa_context_set_card_profile_by_name': ('pa_operation *',
                                         ['pa_context *',
                                          'char *',
                                          'char *',
                                          'pa_context_success_cb_t',
                                          'void *']),
 'pa_context_set_default_sink': ('pa_operation *',
                                 ['pa_context *',
                                  'char *',
                                  'pa_context_success_cb_t',
                                  'void *']),
 'pa_context_set_default_source': ('pa_operation *',
                                   ['pa_context *',
                                    'char *',
                                    'pa_context_success_cb_t',
                                    'void *']),
 'pa_context_set_event_callback': ('void',
                                   ['pa_context *',
                                    'pa_context_event_cb_t',
                                    'void *']),
 'pa_context_set_name': ('pa_operation *',
                         ['pa_context *',
                          'char *',
                          'pa_context_success_cb_t',
                          'void *']),
 'pa_context_set_port_latency_offset': ('pa_operation *',
                                        ['pa_context *',
                                         'char *',
                                         'char *',
                                         'int64_t',
                                         'pa_context_success_cb_t',
                                         'void *']),
 'pa_context_set_sink_input_mute': ('pa_operation *',
                                    ['pa_context *',
                                     'uint32_t',
                                     'int',
                                     'pa_context_success_cb_t',
                                     'void *']),
 'pa_context_set_sink_input_volume': ('pa_operation *',
                                      ['pa_context *',
                                       'uint32_t',
                                       'pa_cvolume *',
                                       'pa_context_success_cb_t',
                                       'void *']),
 'pa_context_set_sink_mute_by_index': ('pa_operation *',
                                       ['pa_context *',
                                        'uint32_t',
                                        'int',
                                        'pa_context_success_cb_t',
                                        'void *']),
 'pa_context_set_sink_mute_by_name': ('pa_operation *',
                                      ['pa_context *',
                                       'char *',
                                       'int',
                                       'pa_context_success_cb_t',
                                       'void *']),
 'pa_context_set_sink_port_by_index': ('pa_operation *',
                                       ['pa_context *',
                                        'uint32_t',
                                        'char *',
                                        'pa_context_success_cb_t',
                                        'void *']),
 'pa_context_set_sink_port_by_name': ('pa_operation *',
                                      ['pa_context *',
                                       'char *',
                                       'char *',
                                       'pa_context_success_cb_t',
                                       'void *']),
 'pa_context_set_sink_volume_by_index': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'pa_cvolume *',
                                          'pa_context_success_cb_t',
                                          'void *']),
 'pa_context_set_sink_volume_by_name': ('pa_operation *',
                                        ['pa_context *',
                                         'char *',
                                         'pa_cvolume *',
                                         'pa_context_success_cb_t',
                                         'void *']),
 'pa_context_set_source_mute_by_index': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'int',
                                          'pa_context_success_cb_t',
                                          'void *']),
 'pa_context_set_source_mute_by_name': ('pa_operation *',
                                        ['pa_context *',
                                         'char *',
                                         'int',
                                         'pa_context_success_cb_t',
                                         'void *']),
 'pa_context_set_source_output_mute': ('pa_operation *',
                                       ['pa_context *',
                                        'uint32_t',
                                        'int',
                                        'pa_context_success_cb_t',
                                        'void *']),
 'pa_context_set_source_output_volume': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'pa_cvolume *',
                                          'pa_context_success_cb_t',
                                          'void *']),
 'pa_context_set_source_port_by_index': ('pa_operation *',
                                         ['pa_context *',
                                          'uint32_t',
                                          'char *',
                                          'pa_context_success_cb_t',
                                          'void *']),
 'pa_context_set_source_port_by_name': ('pa_operation *',
                                        ['pa_context *',
                                         'char *',
                                         'char *',
                                         'pa_context_success_cb_t',
                                         'void *']),
 'pa_context_set_source_volume_by_index': ('pa_operation *',
                                           ['pa_context *',
                                            'uint32_t',
                                            'pa_cvolume *',
                                            'pa_context_success_cb_t',
                                            'void *']),
 'pa_context_set_source_volume_by_name': ('pa_operation *',
                                          ['pa_context *',
                                           'char *',
                                           'pa_cvolume *',
                                           'pa_context_success_cb_t',
                                           'void *']),
 'pa_context_set_state_callback': ('void',
                                   ['pa_context *',
                                    'pa_context_notify_cb_t',
                                    'void *']),
 'pa_context_set_subscribe_callback': ('void',
                                       ['pa_context *',
                                        'pa_context_subscribe_cb_t',
                                        'void *']),
 'pa_context_stat': ('pa_operation *',
                     ['pa_context *', 'pa_stat_info_cb_t', 'void *']),
 'pa_context_subscribe': ('pa_operation *',
                          ['pa_context *',
                           'pa_subscription_mask_t',
                           'pa_context_success_cb_t',
                           'void *']),
 'pa_context_suspend_sink_by_index': ('pa_operation *',
                                      ['pa_context *',
                                       'uint32_t',
                                       'int',
                                       'pa_context_success_cb_t',
                                       'void *']),
 'pa_context_suspend_sink_by_name': ('pa_operation *',
                                     ['pa_context *',
                                      'char *',
                                      'int',
                                      'pa_context_success_cb_t',
                                      'void *']),
 'pa_context_suspend_source_by_index': ('pa_operation *',
                                        ['pa_context *',
                                         'uint32_t',
                                         'int',
                                         'pa_context_success_cb_t',
                                         'void *']),
 'pa_context_suspend_source_by_name': ('pa_operation *',
                                       ['pa_context *',
                                        'char *',
                                        'int',
                                        'pa_context_success_cb_t',
                                        'void *']),
 'pa_context_unload_module': ('pa_operation *',
                              ['pa_context *',
                               'uint32_t',
                               'pa_context_success_cb_t',
                               'void *']),
 'pa_context_unref': ('void', ['pa_context *']),
 'pa_mainloop_dispatch': ('int', ['pa_mainloop *']),
 'pa_mainloop_free': ('void', ['pa_mainloop *']),
 'pa_mainloop_get_api': ('pa_mainloop_api *', ['pa_mainloop *']),
 'pa_mainloop_get_retval': ('int', ['pa_mainloop *']),
 'pa_mainloop_iterate': ('int', ['pa_mainloop *', 'int', 'int *']),
 'pa_mainloop_new': ('pa_mainloop *', ['void']),
 'pa_mainloop_poll': ('int', ['pa_mainloop *']),
 'pa_mainloop_prepare': ('int', ['pa_mainloop *', 'int']),
 'pa_mainloop_quit': ('void', ['pa_mainloop *', 'int']),
 'pa_mainloop_run': ('int', ['pa_mainloop *', 'int *']),
 'pa_mainloop_set_poll_func': ('void',
                               ['pa_mainloop *', 'pa_poll_func', 'void *']),
 'pa_mainloop_wakeup': ('void', ['pa_mainloop *'])}

# Callbacks.
callbacks = {'pa_context_event_cb_t': ('void',
                           ['pa_context *',
                            'char *',
                            'pa_proplist *',
                            'void *']),
 'pa_context_index_cb_t': ('void', ['pa_context *', 'uint32_t', 'void *']),
 'pa_context_notify_cb_t': ('void', ['pa_context *', 'void *']),
 'pa_context_play_sample_cb_t': ('void',
                                 ['pa_context *', 'uint32_t', 'void *']),
 'pa_context_string_cb_t': ('void',
                            ['pa_context *', 'int', 'char *', 'void *']),
 'pa_context_subscribe_cb_t': ('void',
                               ['pa_context *',
                                'pa_subscription_event_type_t',
                                'uint32_t',
                                'void *']),
 'pa_context_success_cb_t': ('void', ['pa_context *', 'int', 'void *']),
 'pa_module_info_cb_t': ('void',
                         ['pa_context *', 'pa_module_info *', 'int', 'void *']),
 'pa_sink_info_cb_t': ('void',
                       ['pa_context *', 'pa_sink_info *', 'int', 'void *']),
 'pa_sink_input_info_cb_t': ('void',
                             ['pa_context *',
                              'pa_sink_input_info *',
                              'int',
                              'void *'])}
